export default {
  login: 'Ahmed-Saaed',
  id: 86948480,
  node_id: 'MDQ6VXNlcjg2OTQ4NDgw',
  avatar_url: 'https://avatars.githubusercontent.com/u/86948480?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Ahmed-Saaed',
  html_url: 'https://github.com/Ahmed-Saaed',
  followers_url: 'https://api.github.com/users/Ahmed-Saaed/followers',
  following_url:
    'https://api.github.com/users/Ahmed-Saaed/following{/other_user}',
  gists_url: 'https://api.github.com/users/Ahmed-Saaed/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/Ahmed-Saaed/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Ahmed-Saaed/subscriptions',
  organizations_url: 'https://api.github.com/users/Ahmed-Saaed/orgs',
  repos_url: 'https://api.github.com/users/Ahmed-Saaed/repos',
  events_url: 'https://api.github.com/users/Ahmed-Saaed/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/Ahmed-Saaed/received_events',
  type: 'User',
  site_admin: false,
  name: 'Ahmed saaed',
  company: null,
  blog: 'https://www.linkedin.com/in/ahmed-saaed/',
  location: 'Egypt',
  email: null,
  hireable: null,
  bio: "Fine Arts graduated and I love mixing art with the code, it is like you are using both sides of your brain at the same time, don't you agree?",
  twitter_username: null,
  public_repos: 19,
  public_gists: 0,
  followers: 1,
  following: 0,
  created_at: '2021-07-05T06:55:33Z',
  updated_at: '2023-08-18T19:13:40Z',
};
